### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by teri0328** [teri0328/chat-space#10]
# IPアドレス
52.197.181.112

**Comment by yasunamiura** [comment]
地中さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**①グループ名と最新メッセージの下線をなくしましょう**
<img width="1157" alt="ChatSpace" src="https://user-images.githubusercontent.com/52514431/77128350-257e6a80-6a93-11ea-89a4-cc5784db2387.png">
見本
<img width="1184" alt="ChatSpaceSample" src="https://user-images.githubusercontent.com/52514431/77128372-3fb84880-6a93-11ea-960a-a44627e70c0a.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by teri0328** [comment]
訂正致しました。
ご確認の程お願い申し上げます。

**Comment by chiii220** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
